apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate